export type Evidence = {value:number; unit:string; source:string; source_url:string; source_type:string; source_id?:string;citation_key?:string;accounting_basis?:string;period_basis?:string;normalization_state?:string;normalization_note_id?:string;reported_period:string; period_end:string; published_at:string; retrieved_at:string; validation_status:string};
export type MetricRow = {metric:string; raw:number|null; normalization:string; sector_percentile:number|null; weight:number; contribution:number};
export type Scenario = {case:string; low:number|null; high:number|null; mid:number|null; assumptions:Record<string,number>; methods:{method:string;value:number;formula:string;inputs:Record<string,number|boolean>}[]};
export type Company = {rule_trace:{corpus_version:string;rule_ids:string[];source_ids:string[]};calculations:{formula_id:string;metric:string;value:number|null;status:string;reason?:string|null;inputs:unknown}[];symbol:string; company:string; sector:string; profile:{description?:string; official_domain?:string}; market:{price:number|null;observed_at:string|null;source:string;source_url:string;retrieved_at:string}; quality_score:number|null; timing_score:number|null; confidence:number;coverage:number;state:string;eligible:boolean;why:string;why_now:string;why_not:string[];thesis:string;entry_conditions:string[];monitor:string[];invalidation:string[];trim:string[];gate_reasons:string[];missing:string[];margin_of_safety:number|null;metrics:Record<string,number|null>;selected_evidence:Record<string,Evidence>;score_breakdown:{category:string;weight:number;metrics:MetricRow[]}[];valuation:{status:string;fair_value_low:number|null;fair_value_high:number|null;entry_low:number|null;entry_high:number|null;base:number|null;explanation:string;scenarios:Scenario[]};history_sessions:number;history_latest:string|null;price_history:{date:string;close:number}[];corporate_actions:Record<string,unknown>[];exit:{risk_stop:string;thesis_invalidation:string[];valuation_exit:string;portfolio_trim:string};discrepancies:Record<string,unknown>[]};
export type Board = {corpus:Corpus;normalization_notes:Record<string,string>;version:string;as_of:string;market_regime:string;database:{state:string;connected:boolean};market_freshness:{state:string;observed_at:string|null;retrieved_at:string;age_days:number|null};coverage:{registered:number;eligible:number;with_primary_financials:number;universe_status:string};technical:TechnicalBoard;preliminary:{focus:PreliminaryCompany[];comparisons:PreliminaryCompany[];methodology:string;counts:{compared:number;screen_passed:number}};top3:Company[];top3_message:string;companies:Company[];sectors:{slug:string;name:string;registered:number;top3:Company[]}[];sources:{name:string;type:string;url:string|null;status:string}[];market_transports:{url:string;observed_at:string|null;error:string|null}[];discrepancies:Record<string,unknown>[];alerts:string[];config:{weights:Record<string,number>;gates:Record<string,number>;scenarios:Record<string,Record<string,number>>};backtest:{status:string;sample_size:number;period:string|null;returns:number|null;drawdown:number|null;hit_rate:number|null;methodology:string;limitations:string[]}};

export type PreliminaryCompany = {symbol:string;company:string;sector:string;decision:string;npl:number;capital_adequacy:number;price:number|null;eps:number|null;pe:number|null;why:string;next_step:string;period_end:string;source_url:string};

export type TechnicalCompany = {symbol:string;company:string;sector:string;date:string;sessions:number;close:number;observed_price:number|null;observed_at:string|null;score:number|null;return_63d:number;return_20d:number;sma50:number;sma200:number|null;turnover_20d:number|null;volume_ratio:number|null;atr14:number|null;entry_trigger:number|null;risk_line:number|null;reference_2r:number|null;trend:boolean;setup:boolean;confirmed:boolean;state:string;why:string;action:string;warnings:string[];source_url:string;archive_comparison:{date:string|null;difference_pct:number|null;status:string;source_url:string|null}};
export type TechnicalBoard = {rows:TechnicalCompany[];leaders:TechnicalCompany[];excluded:{symbol:string;reason:string}[];counts:{analysed:number;comparable:number;setups:number;breakouts:number;above_trend:number};breadth_pct:number|null;regime:string;regime_note:string;latest_date:string|null;method:{name:string;description:string;entry_rule:string;exit_rule:string;limitations:string;references:{title:string;url:string;scope:string}[]}};

export type Corpus = {version:string;sha256:string;drive_documents:Record<string,string>;sources:{source_id:string;citation_key:string;title:string;canonical_url:string;archive_status:string}[];formulas:{formula_id:string;sector:string;name:string;formula_or_method:string;source_basis:string}[];sector_rules:{rule_id:string;sector:string;metric_or_rule:string;source_basis:string;hard_gate:string}[]};
