"use client";
import {useState} from "react";
import Link from "next/link";
import type {Board,Company} from "./contracts";
const cash=(v:number|null|undefined)=>v==null?"Missing":`Rs ${v.toLocaleString("en-US",{maximumFractionDigits:2})}`;
const pct=(v:number|null|undefined)=>v==null?"Missing":`${(v*100).toFixed(2)}%`;

export function DecisionEvidence({data}:{data:Board}){
 const [sector,setSector]=useState("banks");
 const [multiple,setMultiple]=useState(15);
 const reported=data.companies.filter(c=>c.selected_evidence.eps?.source_type.startsWith("company_"));
 const comparisons=data.preliminary.comparisons.filter(c=>c.sector===sector);
 return <>
 <section className="decision-section" aria-labelledby="focus-title"><div className="section-head"><div><p className="eyebrow">Your starting point</p><h2 id="focus-title">Where to focus — and why</h2></div><span>{data.coverage.with_primary_financials} companies with primary evidence</span></div><p>Start with the companies below for further research. Their reported credit quality and capital pass the preliminary screen. The action today is <strong>watch / wait</strong> until earnings, valuation and price confirmation support an entry.</p><div className="grid three">{data.preliminary.focus.map((c,i)=><article className="card research-card focus-card" key={c.symbol}><p className="eyebrow">{c.sector==="banks"?"Banking":"Microfinance"} · research focus {i+1}</p><h2><Link href={`/company/${c.symbol}`}>{c.symbol} ↗</Link></h2><p>{c.company}</p><span className="badge caution">WATCH / WAIT</span><div className="research-stats"><div>NPL<strong>{pct(c.npl)}</strong></div><div>Capital adequacy<strong>{pct(c.capital_adequacy)}</strong></div></div><p>{c.why}</p><p><strong>Observed price:</strong> {cash(c.price)}{c.pe!=null?` · reported P/E ${c.pe.toFixed(1)}×`:" · earnings valuation not yet supported"}</p><p><strong>Before investing:</strong> {c.next_step}</p><a className="small" href={c.source_url} target="_blank" rel="noreferrer">Primary report · period ends {c.period_end} ↗</a></article>)}</div><details className="screen-method"><summary>How this shortlist is selected</summary><p>{data.preliminary.methodology}</p></details></section>
 <section className="card research-card decision-section"><p className="eyebrow">Current financial reports</p><h2>What the price is asking you to believe</h2><p>Reported full-year EPS gives an initial earnings comparison. It is not normalized earning power. A higher multiple needs stronger, sustainable growth to justify it.</p><div className="table-wrap"><table><thead><tr><th>Company</th><th>Observed price</th><th>Reported EPS</th><th>Indicative P/E</th><th>EPS change</th><th>Reading / next action</th></tr></thead><tbody>{reported.map(c=><tr key={c.symbol}><td><Link href={`/company/${c.symbol}`}><strong>{c.symbol} ↗</strong></Link><small className="company"><a href={c.selected_evidence.eps.source_url}>Official Q4 report ↗</a></small></td><td>{cash(c.market.price)}</td><td>{cash(c.metrics.eps)}</td><td>{c.metrics.pe==null?"Unavailable":`${c.metrics.pe.toFixed(1)}×`}</td><td>{pct(c.metrics.eps_growth)}</td><td>{financialReading(c)}</td></tr>)}</tbody></table></div><label className="multiple-control">Explore an assumed earnings multiple: <strong>{multiple}×</strong><input aria-label="Assumed earnings multiple" type="range" min="8" max="25" step="1" value={multiple} onChange={e=>setMultiple(Number(e.target.value))}/></label><p className="small">Illustrative arithmetic: reported EPS × your assumed P/E. The 20% buffer is a planning discount to that scenario, not an approved entry price. It assumes unchanged earnings and omits the balance sheet, growth and sector-specific risks. Life-insurance actuarial value cannot be reduced to this calculation.</p><div className="grid three">{reported.filter(c=>["banks","manufacturing"].includes(c.sector)).map(c=><div className="scenario" key={c.symbol}><h3>{c.symbol} · earnings scenario</h3><p>{cash(c.metrics.eps)} × {multiple} = <strong>{cash((c.metrics.eps??0)*multiple)}</strong></p><p>With a 20% planning buffer: <strong>{cash((c.metrics.eps??0)*multiple*.8)}</strong></p></div>)}</div></section>
 <section className="card research-card decision-section"><div className="section-head"><div><p className="eyebrow">Primary regulatory comparison</p><h2>Credit quality and capital</h2></div><select aria-label="Financial comparison sector" value={sector} onChange={e=>setSector(e.target.value)}><option value="banks">Commercial banks</option><option value="microfinance">Microfinance</option></select></div><p>{data.preliminary.counts.compared} companies compared. These are provisional July 2026 regulatory reports, supplemented by admitted company filings. NRB figures can differ from NFRS financial statements.</p><div className="table-wrap"><table><thead><tr><th>Company</th><th>NPL</th><th>Capital adequacy</th><th>Observed price</th><th>Preliminary decision</th><th>Evidence</th></tr></thead><tbody>{comparisons.map(c=><tr key={c.symbol}><td><Link href={`/company/${c.symbol}`}><strong>{c.symbol} ↗</strong></Link></td><td>{pct(c.npl)}</td><td>{pct(c.capital_adequacy)}</td><td>{cash(c.price)}</td><td>{c.decision}</td><td><a href={c.source_url} target="_blank" rel="noreferrer">{c.period_end} report ↗</a></td></tr>)}</tbody></table></div><p className="small">“Research first” is a limited financial screen, not a buy recommendation. Microfinance regulatory ROE is based on core capital; it is kept separate from accounting ROE.</p></section>
 </>;
}

function financialReading(c:Company){
 const m=c.metrics;
 if(c.sector==="life-insurance")return "Wait for actuarial/reserve and sustainable-profit analysis; the reported earnings multiple alone cannot value this insurer.";
 if(c.sector==="manufacturing")return `Revenue change ${pct(m.revenue_growth)}. Review demand, margins and cash conversion before paying for growth.`;
 if(c.sector==="banks")return `ROE ${pct(m.roe)}; NPL ${pct(m.npl)}. Compare the earnings multiple with sustainable returns and provisioning risk.`;
 return "Review sustainable earnings and sector-specific risks before setting an entry price.";
}
