"use client";
import {useCallback,useEffect,useState} from "react";
import Link from "next/link";
import type {Board,Company} from "./contracts";
import {caseStudies} from "./methodology";
const money=(n:number|null|undefined)=>n==null?"Unavailable":`Rs ${new Intl.NumberFormat("en-US",{maximumFractionDigits:0}).format(n)}`;
const score=(n:number|null)=>n==null?"Unavailable":`${n}/100`;
const range=(l:number|null,h:number|null)=>l==null||h==null?"Unavailable":`${money(l)}–${money(h)}`;
const percent=(v:number|null)=>v==null?"Unavailable":`${(v*100).toFixed(1)}%`;
function Bullets({items}:{items:string[]}){return <ul>{items.map((s,i)=><li key={i}>{s}</li>)}</ul>;}
const researchSymbols=["NABIL","CHCL","SHIVM","CBBL","NLIC","SICL"];
function EvidenceOverview({companies}:{companies:Company[]}){
 const rows=researchSymbols.map(symbol=>companies.find(c=>c.symbol===symbol)).filter((c):c is Company=>Boolean(c));
 return <section className="card research-card"><p className="eyebrow">Available evidence</p><h2>Prices, financials and research gaps</h2><p>These six companies cover the sector models. This is a research coverage table. It does not recommend buying any of them. P/E uses reported EPS and an unconfirmed secondary price; it is not fair value.</p><div className="table-wrap"><table className="evidence-overview"><thead><tr><th>Company</th><th>Observed price</th><th>Reported EPS</th><th>Indicative P/E</th><th>20-session turnover</th><th>Price sessions</th><th>Financial evidence</th></tr></thead><tbody>{rows.map(c=><tr key={c.symbol}><td><Link href={`/company/${c.symbol}`}><strong>{c.symbol} ↗</strong></Link><small className="company">{c.sector.replaceAll("-"," ")}</small></td><td>{money(c.market.price)}<small className="company">{c.market.observed_at?.slice(0,10)??"No timestamp"}</small></td><td>{c.metrics.eps==null?"Missing":`Rs ${c.metrics.eps.toFixed(2)}`}<small className="company">{c.selected_evidence.eps?.reported_period??"No admitted report"}</small></td><td>{c.metrics.pe==null?"Unavailable":`${c.metrics.pe.toFixed(1)}×`}</td><td>{money(c.metrics.turnover_20d)}</td><td>{c.price_history.length}<small className="company">{c.price_history.at(-1)?.date??"Unavailable"}</small></td><td>{Object.values(c.selected_evidence).filter(e=>e.source_type!=="secondary").length} primary metrics<small className="company">{c.missing.length} critical fields missing</small></td></tr>)}</tbody></table></div><p className="small">Historical prices are secondary and unadjusted. Corporate actions, official market confirmation, earning power and comparable peer evidence still require validation. <Link href="/sources">See exactly which sources are connected →</Link></p></section>;
}
function Candidate({company:c,rank}:{company:Company;rank?:number}){return <article className="card research-card">
 <div className="candidate-heading"><div><p className="eyebrow">{rank?`#${rank} research candidate`:c.sector.replaceAll("-"," ")}</p><h2><Link href={`/company/${c.symbol}`}>{c.symbol} ↗</Link></h2><p>{c.company}</p></div><span className={`badge ${c.eligible?"positive":"caution"}`}>{c.state}</span></div>
 <div className="research-stats"><div>Quality<strong>{score(c.quality_score)}</strong></div><div>Entry / timing<strong>{score(c.timing_score)}</strong></div><div>Confidence<strong>{score(c.confidence)}</strong></div><div>Observed price<strong>{money(c.market.price)}</strong></div></div>
 <dl className="ranges"><div><dt>Base fair value</dt><dd>{range(c.valuation.fair_value_low,c.valuation.fair_value_high)}</dd></div><div><dt>Preferred entry range</dt><dd>{range(c.valuation.entry_low,c.valuation.entry_high)}</dd></div><div><dt>Margin of safety</dt><dd>{percent(c.margin_of_safety)}</dd></div></dl>
 <div className="grid two"><div><h3>Why it qualifies</h3><p>{c.why}</p><h3>Why now / why wait</h3><p>{c.why_now}</p></div><div><h3>Why this could be wrong</h3><Bullets items={c.why_not}/></div></div>
 {c.gate_reasons.length>0&&<details><summary>Evidence gaps ({c.gate_reasons.length})</summary><Bullets items={c.gate_reasons}/></details>}
 <p className="small muted">Observed {c.market.observed_at??"Unavailable"} · <a href={c.market.source_url} target="_blank" rel="noreferrer">{c.market.source}</a></p></article>;}
function CompanyDetail({company:c}:{company:Company}){return <><Candidate company={c}/>
 <div className="grid two"><section className="card research-card"><h2>Thesis and monitoring</h2><p>{c.thesis}</p><h3>Entry conditions</h3><Bullets items={c.entry_conditions}/><h3>Monitor</h3><Bullets items={c.monitor}/><h3>Thesis invalidation</h3><Bullets items={c.invalidation}/></section><section className="card research-card"><h2>Exit and trim reasoning</h2><h3>Risk stop</h3><p>{c.exit.risk_stop}</p><h3>Valuation exit</h3><p>{c.exit.valuation_exit}</p><h3>Portfolio / trim</h3><p>{c.exit.portfolio_trim}</p><Bullets items={c.trim}/></section></div>
 <section className="card research-card"><h2>Business and financial evidence</h2><p>{c.profile.description??"Unavailable"}</p><div className="table-wrap"><table><thead><tr><th>Metric</th><th>Value</th><th>Period</th><th>Source</th></tr></thead><tbody>{Object.entries(c.metrics).map(([k,v])=><tr key={k}><td>{k}</td><td>{v??"Unavailable"}</td><td>{c.selected_evidence[k]?.reported_period??"Derived / unavailable"}</td><td>{c.selected_evidence[k]?<a href={c.selected_evidence[k].source_url}>{c.selected_evidence[k].source}</a>:"No admitted source"}</td></tr>)}</tbody></table></div><p>Financial, dividend and governance history requires admitted reports. Missing information does not imply good performance.</p></section>
 <section className="card research-card"><h2>Bear / base / bull valuation</h2><p>{c.valuation.explanation}</p><div className="grid three">{c.valuation.scenarios.map(s=><div className="scenario" key={s.case}><h3>{s.case}</h3><strong>{range(s.low,s.high)}</strong><p>Cost of equity {percent(s.assumptions.cost_equity)} · growth {percent(s.assumptions.growth)}</p>{s.methods.map(m=><details key={m.method}><summary>{m.method}: {money(m.value)}</summary><p>{m.formula}</p><pre>{JSON.stringify(m.inputs,null,2)}</pre></details>)}{s.methods.length<2&&<p>Fewer than two methods supported.</p>}</div>)}</div></section>
 <section className="card research-card"><h2>Score calculation breakdown</h2><div className="table-wrap"><table><thead><tr><th>Metric</th><th>Raw</th><th>Sector percentile</th><th>Weight</th><th>Contribution</th></tr></thead><tbody>{c.score_breakdown.flatMap(g=>g.metrics).map(m=><tr key={m.metric}><td>{m.metric}<small className="company">{m.normalization}</small></td><td>{m.raw??"Unavailable"}</td><td>{m.sector_percentile?.toFixed(1)??"Unavailable"}</td><td>{percent(m.weight)}</td><td>{m.contribution.toFixed(1)}</td></tr>)}</tbody></table></div><p>Final quality: {score(c.quality_score)}. Missing contributions are zero; their weights are never redistributed.</p></section>
 <section className="card research-card"><h2>Historical record</h2><p>{c.price_history.length} price sessions · {c.corporate_actions.length} admitted corporate actions.</p>{c.price_history.length?<div className="table-wrap"><table><tbody>{c.price_history.slice(-20).map(p=><tr key={p.date}><td>{p.date}</td><td>{money(p.close)}</td></tr>)}</tbody></table></div>:<p>Historical valuation and score history unavailable until durable ingestion is connected.</p>}</section></>;}
export default function ResearchView({path}:{path:string[]}){
 const [page,setPage]=useState(0);
 const [data,setData]=useState<Board|null>(null),[error,setError]=useState<string|null>(null),[loading,setLoading]=useState(false),[search,setSearch]=useState("");
 const load=useCallback(()=>{setLoading(true);setError(null);fetch("/api/research",{cache:"no-store"}).then(async r=>{if(!r.ok)throw Error("Research evidence is unavailable");return r.json();}).then(setData).catch(e=>setError(String(e))).finally(()=>setLoading(false));},[]);
 useEffect(()=>{load();},[load]);
 const route=path[0]??"board";
 const title=route==="board"?"Investment decisions,\nwith the evidence in view.":route==="company"?`${path[1]?.toUpperCase()??"Company"} research`:route==="methodology"?"How the engine reasons.":route==="sources"?"Evidence before conviction.":route==="backtests"?"Test the thesis over time.":route==="sectors"?"Sector research.":"Research candidates.";
 return <main className="shell decision-shell"><header className="hero"><div><p className="eyebrow">NPSE Investment Decision Engine</p><h1 className="research-title">{title}</h1><p className="lede">Company quality. A justified price. Clear conditions for waiting, entering and exiting.</p></div><button className="refresh" onClick={load} disabled={loading}>{loading?"Checking evidence…":"Check latest evidence ↻"}</button></header>
 {error&&<div className="notice" role="alert">{error}. No investment ranking is issued. <button onClick={load}>Retry</button></div>}{!data&&!error&&<div className="card research-card" role="status">Checking prices, financial evidence and eligibility gates…</div>}
 {data&&<><section className="health-strip"><div><span>Market observation</span><b>{data.market_freshness.state}</b><small>{data.market_freshness.observed_at??"Unavailable"}</small></div><div><span>Coverage</span><b>{data.coverage.eligible} eligible / {data.coverage.registered} registered</b><small>Official exchange completeness verification pending</small></div><div><span>Durable history</span><b>{data.database.state}</b><small>Postgres research store</small></div><div><span>Market regime</span><b>Unverified</b><small>Independent confirmation required</small></div></section>{data.alerts.map(a=><div className="notice" key={a}>{a}</div>)}
 {(route==="board"||route==="candidates")&&<><EvidenceOverview companies={data.companies}/><div className="section-head decision-section"><div><span>Evidence-qualified opportunities</span><h2>Top 3 current NPSE research candidates</h2></div><span>{data.top3.length}/3 displayed</span></div>{data.top3.length?data.top3.map((c,i)=><Candidate key={c.symbol} company={c} rank={i+1}/>):<section className="card research-card empty-research"><span className="badge caution">INSUFFICIENT DATA</span><h2>No candidate currently meets the evidence threshold.</h2><p>Prices alone cannot justify an investment. Authoritative financials, comparable sector evidence, historical liquidity and supported valuation must pass first.</p><Link href="/sources">Inspect source coverage →</Link></section>}<section className="decision-section"><h2>Sector opportunity map</h2><div className="grid three">{data.sectors.map(s=><Link className="card sector-tile" key={s.slug} href={`/sectors/${s.slug}`}><span>{s.name} ↗</span><strong>{s.top3.length} qualified</strong><small>{s.registered} registered · separate sector model</small></Link>)}</div></section><section className="decision-section"><div className="section-head"><h2>Watch / wait and rejected candidates</h2><input aria-label="Search registered companies" placeholder="Search symbol or company" value={search} onChange={e=>{setSearch(e.target.value);setPage(0);}}/></div>{data.companies.filter(c=>`${c.symbol} ${c.company}`.toLowerCase().includes(search.toLowerCase())).slice(page*12,page*12+12).map(c=><Candidate key={c.symbol} company={c}/>)}<div className="pagination"><button disabled={page===0} onClick={()=>setPage(p=>p-1)}>Previous</button><span>Page {page+1}</span><button disabled={(page+1)*12>=data.companies.filter(c=>`${c.symbol} ${c.company}`.toLowerCase().includes(search.toLowerCase())).length} onClick={()=>setPage(p=>p+1)}>Next</button></div><p className="small muted">Labels such as “good company / too expensive” or “cheap / weak business” require supporting evidence.</p></section></>}
 {route==="sectors"&&(path[1]?<><h2>{data.sectors.find(s=>s.slug===path[1])?.name??"Unknown sector"}</h2><p>Top 3 in this sector: {data.sectors.find(s=>s.slug===path[1])?.top3.length??0} meet the threshold.</p>{data.companies.filter(c=>c.sector===path[1]).map(c=><Candidate key={c.symbol} company={c}/>)}</>:<div className="grid three">{data.sectors.map(s=><Link className="card sector-tile" key={s.slug} href={`/sectors/${s.slug}`}><h2>{s.name}</h2><p>{s.top3.length} qualified / {s.registered} registered</p></Link>)}</div>)}
 {route==="company"&&(data.companies.find(c=>c.symbol===path[1]?.toUpperCase())?<CompanyDetail company={data.companies.find(c=>c.symbol===path[1]?.toUpperCase())!}/>:<section className="card research-card"><h2>Company not registered</h2><p>This symbol is outside the admitted universe.</p></section>)}
 {route==="methodology"&&<><section className="card research-card"><h2>Three separate judgments</h2><p>Investment quality describes the business and valuation. Entry / timing examines price versus value, trend and liquidity. Data confidence measures whether either judgment is supported. Strong momentum cannot override fundamental weakness.</p><h3>Default quality weights</h3><table><tbody>{Object.entries(data.config.weights).map(([k,v])=><tr key={k}><td>{k}</td><td>{percent(v)}</td></tr>)}</tbody></table><h3>Normalization and missing data</h3><p>Within-sector empirical midrank percentiles; clip at peer 5th/95th percentiles; require five comparable peers. Ties produce midpoints. Missing metrics contribute zero and coverage below 80% withholds the score.</p><h3>Eligibility and freshness</h3><p>All critical primary financial fields, confidence ≥75, quality ≥65, timing ≥50, 50 observed sessions, 20-session mean turnover ≥Rs 1 million and margin of safety ≥20%. Official or independent market-price confirmation is required. Market age above three calendar days blocks eligibility conservatively, including holidays. Financial period age above 160 days blocks eligibility. Retrieval time never replaces observation time.</p><h3>Sector valuation</h3><p>Banks and microfinance: justified P/B and normalized P/E. Hydro and manufacturing: EV/EBITDA, normalized P/E and FCFE DCF where supported. Hydro uses finite project life, no perpetual terminal value. Life and non-life insurance have different reserves, solvency and underwriting gates. Require two methods for a fair-value range. Scenario multiples and discount rates are explicit research choices requiring review.</p></section><h2 className="decision-section">Documented principles → implementation choices</h2><p>Documented investor case studies, not a ranking of the best investors. None endorses this engine or its weights.</p><div className="grid two">{caseStudies.map(s=><article className="card research-card" key={s.name}><h2>{s.name}</h2><h3>Documented principle / evidence</h3><p>{s.principle}</p><h3>NPSE implementation choice</h3><p>{s.choice}</p><a href={s.url} target="_blank" rel="noreferrer">{s.source} ↗</a></article>)}</div></>}
 {route==="sources"&&<><section className="card research-card"><h2>Provenance and discrepancies</h2><p>Official filings outrank secondary observations. Compare material conflicts only for the same period and unit. Differences above 3% block positive states. YONEPSE's two transports are one provider, not independent corroboration.</p><p>Observed: {data.market_freshness.observed_at??"Unavailable"}. Retrieved: {data.market_freshness.retrieved_at}. Discrepancies: {data.discrepancies.length}. No observed conflict does not prove agreement.</p><div className="table-wrap"><table><thead><tr><th>Source</th><th>Role</th><th>Actual status</th></tr></thead><tbody>{data.sources.map(s=><tr key={s.name}><td>{s.url?<a href={s.url}>{s.name}</a>:s.name}</td><td>{s.type}</td><td>{s.status}</td></tr>)}</tbody></table></div><h3>Transport health</h3>{data.market_transports.map(s=><p key={s.url}><a href={s.url}>{s.url}</a> · {s.error??s.observed_at??"Timestamp unavailable"}</p>)}</section>{data.companies.filter(c=>c.profile.official_domain).map(c=><section className="card research-card" key={c.symbol}><h2><Link href={`/company/${c.symbol}`}>{c.symbol}</Link> evidence</h2><p>{Object.keys(c.selected_evidence).length} admitted metrics · {percent(c.coverage)} critical coverage.</p><Bullets items={c.gate_reasons}/></section>)}</>}
 {route==="backtests"&&<section className="card research-card"><span className="badge caution">{data.backtest.status}</span><h2>No performance claim without point-in-time evidence.</h2><p>{data.backtest.methodology}</p><div className="research-stats"><div>Sample size<strong>{data.backtest.sample_size}</strong></div><div>Returns<strong>Unavailable</strong></div><div>Drawdown<strong>Unavailable</strong></div><div>Hit rate<strong>Unavailable</strong></div></div><Bullets items={data.backtest.limitations}/><p>The walk-forward module exists. A complete historical archive, adjusted outcomes and lower-ranked comparison cohort are required before results can be published.</p></section>}
 {!['board','candidates','sectors','company','methodology','sources','backtests'].includes(route)&&<p>Page not found. <Link href="/">Return to Decision Board</Link></p>}
 <footer className="small muted decision-section">Engine {data.version} · research run {data.as_of} · Research supports your decision. No brokerage orders or automatic trades.</footer></>}</main>;
}
