import type {Company,Corpus} from "./contracts";
import recovery from "../data/drive-recovery-09.json";

export function CompanyTrace({company:c,notes,corpus}:{company:Company;notes:Record<string,string>;corpus:Corpus}){
 return <section className="card research-card"><h2>Rule and calculation evidence</h2><p>Corpus v{c.rule_trace.corpus_version} · quality, valuation, timing, confidence and thesis risk remain separate. Missing inputs withhold calculations.</p><p>Sector rules: {c.rule_trace.rule_ids.join(" · ")}</p><details><summary>Methodological source IDs and citation keys</summary>{corpus.sources.filter(r=>c.rule_trace.source_ids.includes(r.source_id)).map(r=><p key={r.source_id}><a href={r.canonical_url}>{r.source_id} · {r.citation_key} ↗</a></p>)}</details><div className="table-wrap"><table><thead><tr><th>Observation</th><th>Source ID / citation</th><th>Reporting basis</th><th>Availability / retrieval</th><th>Validation</th></tr></thead><tbody>{Object.entries(c.selected_evidence).filter(([,e])=>e.source_type!=="secondary").map(([metric,e])=><tr key={metric}><td>{metric}</td><td><a href={e.source_url}>{e.source_id??"Supplemental evidence"}</a><small className="company">{e.citation_key}</small></td><td>{e.reported_period}<small className="company">{e.accounting_basis??"As disclosed; comparability review required"}</small></td><td>{e.published_at}<small className="company">{e.retrieved_at}</small></td><td>{e.normalization_state} / {e.validation_status}<small className="company">{e.normalization_note_id?notes[e.normalization_note_id]:"No normalization note"}</small></td></tr>)}</tbody></table></div>{c.calculations.map((r,i)=><details key={`${r.formula_id}-${i}`}><summary>{r.formula_id} · {r.metric} · {r.status} {r.value==null?"":r.value.toLocaleString()}</summary><p>{r.reason}</p><pre>{JSON.stringify(r.inputs,null,2)}</pre></details>)}</section>;
}

export function CorpusPanel({corpus:c}:{corpus:Corpus}){
 return <section className="card research-card"><h2>Research Corpus v{c.version}</h2><p>{c.sources.length} registered sources · {c.formulas.length} formula entries · six separate sector families. Methodology citations establish rule authority; source health states which data feeds are connected.</p><p><a href={recovery.files.find(f=>f.key==="npse_reference")!.url}>Recovered implementation reference ↗</a> · Snapshot SHA-256: <code>{c.sha256.slice(0,16)}…</code></p><details><summary>Sector rules and evidence gates</summary><div className="table-wrap"><table><thead><tr><th>Rule</th><th>Sector / metric</th><th>Source basis</th><th>Gate</th></tr></thead><tbody>{c.sector_rules.map(r=><tr key={r.rule_id}><td>{r.rule_id}</td><td>{r.sector}<small className="company">{r.metric_or_rule}</small></td><td>{r.source_basis}</td><td>{r.hard_gate}</td></tr>)}</tbody></table></div></details><details><summary>Formula registry</summary>{c.formulas.map(f=><p key={f.formula_id}><strong>{f.formula_id} · {f.name}</strong><br/>{f.formula_or_method}<br/><small>{f.source_basis}</small></p>)}</details><details><summary>37 source IDs and canonical addresses</summary>{c.sources.map(s=><p key={s.source_id}><a href={s.canonical_url}>{s.source_id} · {s.citation_key} · {s.title} ↗</a><small className="company">{s.archive_status}</small></p>)}</details></section>;
}
